### ISSUE TITLE
sfdx force --help is not working

### ISSUE THREAD

**Issue by priyanshu2709** [forcedotcom/sfdx-dreamhouse#126]
when i am trying to execute "sfdx force --help"  it is not working.
![image](https://cloud.githubusercontent.com/assets/6105706/23438564/6583406c-fe38-11e6-98b8-174b8c14186f.png)

**Comment by amphro** [comment]
It doesn't look like you have the sfdx binary installed. Please use the setup guide from the pilot chatter group. If you are not part of the pilot, you can join the waitlist here: http://go.pardot.com/l/27572/2017-01-23/6gh89x
