### ISSUE TITLE
Getting error while creating scratch org

### ISSUE THREAD

**Issue by priyanshu2709** [forcedotcom/sfdx-dreamhouse#129]
![image](https://cloud.githubusercontent.com/assets/6105706/25002618/fea7cf0e-2068-11e7-8426-725f4bae640d.png)
I am getting error while creating scratch org. Please help me..

**Comment by amphro** [comment]
This is a known issue. Refer to the pilot chatter group. https://org62.lightning.force.com/one/one.app#/sObject/0D50M000037AVcnSAG/view
