### ISSUE TITLE
Unable to create new SFDX project - launch throwing NullPointer error

### ISSUE THREAD

**Issue by priyapanigrahy** [forcedotcom/sfdx-dreamhouse#141]
<img width="1024" alt="screen shot 2017-07-08 at 8 36 57 pm" src="https://user-images.githubusercontent.com/1229829/27986507-5235d40c-641d-11e7-9ae6-0083759ed682.png">

See the attached screenshot. Getting error when I trying to create a new project of type SFDX project. 
Using Mac installer (my mac version 10.12.5). I was very excited to start my first project but unfortunately, I have to wait for more weeks I guess. let me know if you need any further information.

**Comment by vazexqi** [comment]
@priyapanigrahy - Could you provide the following details?

**Force.com IDE version**: Go to Force.com IDE > About Force.com IDE

**SFDX CLI and sfdx plugin version**: Go to a terminal and issue `sfdx -v` and `sfdx plugins`

**Java version**:

**Comment by priyapanigrahy** [comment]
I doubt I have installed sfdx command line. I have installed "force" command line but not sfdx. Do you mind to send me the npm link to install sfdx.  That could be the reason I m getting the above launch error.

**Comment by priyapanigrahy** [comment]
Force.com IDE
Version: R-Beta-201706260926
Build id: Beta

java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)

**Comment by vazexqi** [comment]
@priyapanigrahy - Yeah, missing the SFDX command line is likely the cause of the problem. Please go to https://developer.salesforce.com/tools/sfdxcli to download it.

FYI, this main entry post has links to other resources of SFDX that you might be interested in https://developer.salesforce.com/blogs/developer-relations/2017/06/introducing-salesforce-dx-open-beta.html

**Comment by vazexqi** [comment]
@priyapanigrahy - I am going to mark this issue as closed. The root cause should be that you do not have the SFDX CLI installed. 

If you are still having this issue after installing it, please feel free to re-open this issue.
